[package]
name = "superdev_quiz"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
solana-sdk="1.15.2"
serde = { version = "1.0", features = ["derive"] }
derive_more = "2.0.1"
spl-token = "8.0.0"
serde_json = "1.0.140"
bs58 = "0.5.1"
